import type { Metadata } from "next";
import "./globals.css";
import { Bungee } from "next/font/google";
import { TeamProvider } from "@/contexts/TeamContext";

const bungee = Bungee({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Tech Inoviq Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${bungee.className}`}>
        <TeamProvider>
          {children}
        </TeamProvider>
      </body>
    </html>
  );
}
